
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: <%= YAML.load_file("#{Rails.root}/config/application.yml")[Rails.env]['db_username'] %>
  password: <%= YAML.load_file("#{Rails.root}/config/application.yml")[Rails.env]['db_password'] %>
  database: weatherapi_development


test:
  <<: *default
  database: weatherapi_test


production:
  <<: *default
  database: weatherapi_production
  username: weatherapi
  password: <%= ENV["WEATHERAPI_DATABASE_PASSWORD"] %>
